### ISSUE TITLE
SVG font warning in Chrome 28

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/server-configs#147]
Chrome 28 Canary shows the following warning in the DevTools console:

> Resource interpreted as Font but transferred with MIME type `image/svg+xml`: "http://example.com/font/foo.svg#foo".

I _think_ this is a Chrome bug as `image/svg+xml` is the correct MIME type for SVG/SVGZ fonts AFAIK, but I’m still posting it here in case there is something wrong with our MIME type configuration.

The CSS used to load the font is [the FontSpring Bulletproof Syntax™ modified to serve the SVG first](http://www.fontspring.com/blog/smoother-web-font-rendering-chrome):

``` css
@font-face {
    font-family: 'foo';
    src: url('font/foo.eot');
    src: url('font/foo.eot?#iefix') format('embedded-opentype'),
         url('font/foo.svg#foo') format('svg'),
         url('font/foo.woff') format('woff'),
         url('font/foo.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

Filed a Chrome bug: https://code.google.com/p/chromium/issues/detail?id=230297

/cc @paulirish
